// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKnBZFeCwOK5oS-__sGHb80hRsrVJHP8',
    appId: '1:781604174221:web:704822b5dd2751bb4f65c4',
    messagingSenderId: '781604174221',
    projectId: 'master-83bc9',
    authDomain: 'master-83bc9.firebaseapp.com',
    storageBucket: 'master-83bc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnWV1oFrVS0ZW9i0yfMt5RHDGvCJlgczE',
    appId: '1:781604174221:android:6fffd45da315cef04f65c4',
    messagingSenderId: '781604174221',
    projectId: 'master-83bc9',
    storageBucket: 'master-83bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQd86MLRqofdYLCgILJDwlLNrIixZ9nw',
    appId: '1:781604174221:ios:634651fa9d02deed4f65c4',
    messagingSenderId: '781604174221',
    projectId: 'master-83bc9',
    storageBucket: 'master-83bc9.firebasestorage.app',
    iosBundleId: 'com.example.master',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQd86MLRqofdYLCgILJDwlLNrIixZ9nw',
    appId: '1:781604174221:ios:634651fa9d02deed4f65c4',
    messagingSenderId: '781604174221',
    projectId: 'master-83bc9',
    storageBucket: 'master-83bc9.firebasestorage.app',
    iosBundleId: 'com.example.master',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJKnBZFeCwOK5oS-__sGHb80hRsrVJHP8',
    appId: '1:781604174221:web:dc9a91e85ad8bb9e4f65c4',
    messagingSenderId: '781604174221',
    projectId: 'master-83bc9',
    authDomain: 'master-83bc9.firebaseapp.com',
    storageBucket: 'master-83bc9.firebasestorage.app',
  );
}
